name: Odds Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Executa no início de cada hora

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install firebase-admin requests

      - name: Run Scraper
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
          ODDS_API_KEY: ${{ secrets.ODDS_API_KEY }}
        run: python scraper.py

