name: Odds Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '45 * * * *' # Executa no minuto 45 de cada hora

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies and Playwright
        run: |
          python -m pip install --upgrade pip
          # Instala dependências do Firebase e a biblioteca Playwright
          pip install firebase-admin lxml playwright
          # Instala o navegador Chromium que o Playwright usará para o scraping
          playwright install chromium --with-deps

      - name: Run Scraper
        # Remove a variável de ambiente ODDS_API_KEY, pois não é mais usada.
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: python scraper.py
