name: Odds Scraper

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # Updated to run every 30 mins to be safer

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 firebase-admin selenium webdriver-manager

      - name: Run Scraper
        env:
          FIREBASE_CREDENTIALS: ${{ secrets.FIREBASE_CREDENTIALS }}
        run: python scraper.py

